### ISSUE TITLE
Header has ugly font

### ISSUE THREAD

**Issue by michalbe** [Wasiak/King-s-books#15]
The header you've created is ugly:
![screen-2015 03 17 12 59 05](https://cloud.githubusercontent.com/assets/347657/6686843/6b54e728-cca5-11e4-8df6-ba06040d0ae1.png)

I suggest you to choose one of the fonts from [Google Web Fonts](http://www.google.com/fonts) and use it as a header font.

**Comment by Wasiak** [comment]
fixed ;)
